- name: killall Dock
  command: killall Dock
  ignore_errors: yes

- name: killall Finder
  command: killall Finder
  ignore_errors: yes

- name: killall SystemUIServer
  command: killall SystemUIServer
  ignore_errors: yes

- name: launchctl load limit.maxfiles
  command: launchctl load -w /Library/LaunchDaemons/limit.maxfiles.plist